### ISSUE TITLE
quickstart demo 使用报错，新手求告知

### ISSUE THREAD

**Issue by HeminWon** [HastingsYoung/GoCollaborateExamples#1]
你好，最近在研究分布式框架，在使用过程中遇到一些问题，在此处想问下大佬，由于是新手 可能有的问题有点傻，还请多多指教

### 关于报错
在使用examples中的quickstart的时候遇到以下几处报错
1. GoCollaborate -> case.go -> Line:42
bytes, err := ioutil.ReadFile(constants.DEFAULT_CASE_PATH) 
此处读取出的file路径为"./case.json" 导致下图
![image](https://user-images.githubusercontent.com/12121718/40552362-022cac7c-6072-11e8-8cad-43df4435702b.png)
我的理解应该路径为“工程路径+/case.json” 不知是不是像我理解的这样

**Comment by HastingsYoung** [comment]
你的思考是正确的，框架代码本身与工程解耦，配置文件的读写均在工程目录下完成。
